name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --target bin --output bin/ .
    - name: Upload executable
      uses: actions/upload-artifact@v3.1.2
      with:
        name: cms
        path: bin/cms
    
